# hi there again
include: 
  - "Starter, Training, Seln, AIC"
  - "AIO"
  - "Alpha"
  - "AIIO"
  - "FARIO"
  - "wayback_raw"
  - "wayback_pdf"
  - "kactl.pdf"
  - "no highlight.pdf"
  - "Vue test"
  - "ORAC Userscript"
  - "Hyperfast"

exclude:
  - "favicon.ico"
  - "big.cpp"
  - "big.py"

defaults:
  - scope:
      path: ""
    values:
      static: true