# Separate each folder/file into its own quoted string
include: 
  - "Starter, Training, Seln, AIC"
  - "AIO"
  - "Alpha"
  - "AIIO"
  - "FARIO"
  - "wayback_raw"
  - "kactl.pdf"
  - "no highlight.pdf"

# Standard exclusions
exclude: 
  - "_config.yml"
  - "index.html"
  - "files.json"
  - "README.md"
  - ".gitignore"

# Force Jekyll to treat every file found as a static asset
defaults:
  - scope:
      path: ""
    values:
      static: true