include: 
  - "Starter, Training, Seln, AIC"
  - "AIO"
  - "Alpha"
  - "AIIO"
  - "FARIO"
  - "wayback_raw"
  - "kactl.pdf"
  - "no highlight.pdf"

defaults:
  - scope:
      path: ""
    values:
      static: true